-- Verify reveal_transaction_tables:goals on pg

BEGIN;

SET search_path TO :"schema",public;

SELECT
    id,
    created_at,
    goal_id,
    plan_id,
    description,
    priority
FROM goals
WHERE FALSE;

-- check primary key
SELECT 1/COUNT(*)
FROM pg_catalog.pg_constraint
WHERE
conname = 'goals_pkey'
AND contype = 'p'
AND 1 = ALL(conkey);

-- check fk constraints
SELECT 1/COUNT(*)
FROM pg_catalog.pg_constraint
WHERE
conname = 'fk_goals_plan'
AND contype = 'f'
AND 4 = ALL(conkey)
AND 1 = ALL(confkey);

-- lets create the util_exception_query function
CREATE OR REPLACE FUNCTION util_exception_query(text)
  RETURNS SETOF text AS
$func$
DECLARE
    text_msg text;
    text_detail text;
    text_hint text;
BEGIN
    EXECUTE $1;
EXCEPTION WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS text_msg    = MESSAGE_TEXT,
                            text_detail = PG_EXCEPTION_DETAIL,
                            text_hint   = PG_EXCEPTION_HINT;
    RETURN NEXT text_msg;
END
$func$ LANGUAGE plpgsql;
--- end

-- you should not be able to insert a goal without existing plan
SELECT 1/COUNT(*)
FROM util_exception_query(
$$
INSERT INTO goals
VALUES (
    uuid_generate_v1(),
    NOW(),
    'the goal id',
    -- this plan does not exist
    '123e4567-mosh-12d3-a456-426655440000',
    'The description',
    'high-priority'
)
$$) AS output
WHERE output ILIKE '%violates foreign key constraint%';

-- check indices
SELECT 1/COUNT(*)
FROM pg_catalog.pg_indexes
WHERE
schemaname = :'schema'
AND tablename = 'goals'
AND indexname = 'goal_id_idx';

ROLLBACK;
